package co.simplon.sockwork_business.entities;

import jakarta.persistence.*;

@MappedSuperclass // indique que cette classe contient des elements de mapping
abstract class AbstractEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="id")
    private Long id;

    protected AbstractEntity() {
    }

    public Long getId() {
        return id;
    }

    private void setId(Long id) {
        //Id generated by db
        this.id = id;
    }
}
